### ISSUE TITLE
Implementation of Gradient-guided nested sampling

### ISSUE THREAD

**Issue by juehang** [Joshuaalbert/jaxns#136]
**Is your feature request related to a problem? Please describe.**
While nested sampling is implemented in jax in this package, it does not (to my knowledge) make use of jax autograd. There is a recent paper describing a gradient-guided nested sampling method that actually cites this package! https://arxiv.org/pdf/2312.03911.pdf

**Describe the solution you'd like**
I would like an implementation in this package, ideally so that I can use it in numpyro. I do not have time to work full-time on an implementation myself, but I would be interested in a joint-effort as well if that is preferred/needed.

**Additional context**
There is an example pytorch implementation here: https://github.com/Pablo-Lemos/GGNS/tree/main

**Comment by Joshuaalbert** [comment]
Hi thanks for the idea. I've considered this before. I could introduce this as an experimental feature. It would need to be assessed will before becoming part of the core engine. 

The focus of jaxns is fast easy general purpose probabilistic programming. I'm trying to keep the amount implementation experimentation needed by a user to solve their problem to a minimum so they can focus on building better models. To that end I'm not looking to have a library of nested sampling implementations. But I can explore this from an experimental perspective. If the engine can be improved and still remain general purpose and robust with good defaults that solve most problems then it could be an option. This year at the MaxEnt conference I'll discuss the latest nested sampling research with others in the field and plan to update jaxns accordingly.

**Comment by juehang** [comment]
I see, thank you for the update! My initial impression from the paper is that this method allows for nested sampling to be extended to higher dimensional models. My current research interest is in applying bayesian methods to simulation-based inference problems which often have quite large latent spaces, and so I was hoping this would be the best of both worlds between NUTS/HMC (better scaling with large models) and nested sampling (marginal likelihoods and evidence).

I will keep posted for now, then; feel free to reach out if you ever need an early tester!

**Comment by Joshuaalbert** [comment]
You should try out an experimental feature of jaxns: parametrised models. In jaxns you can let some variables be Bayesian and some be pointwise estimates of a prior. When you solve the model it finds the parameter values that maximizes the evidence and gives you the posterior of the rest. This can be really powerful, since a full Bayesian treatment with huge latent spaces is impractical for large dimension. You can use this to have Bayesian hierarchical models that perform well.On Jan 20, 2024 06:53, Juehang Qin ***@***.***> wrote:
I see, thank you for the update! My initial impression from the paper is that this method allows for nested sampling to be extended to higher dimensional models. My current research interest is in applying bayesian methods to simulation-based inference problems which often have quite large latent spaces, and so I was hoping this would be the best of both worlds between NUTS/HMC (better scaling with large models) and nested sampling (marginal likelihoods and evidence).
I will keep posted for now, then; feel free to reach out if you ever need an early tester!

**Comment by juehang** [comment]
Thank you for the suggestion; do you have any papers on this topic? I couldn't find much about this kind of method with a cursory search; I suppose it is similar to profile likelihoods but I was wondering if there are any papers exploring the statistical properties of this procedure, what the limitations are, etc.

**Comment by Joshuaalbert** [comment]
It's novel, and I will write a paper after I answer some of these questions myself. Are you interested in being a part of the paper? If your example use case is a good fit then it could be the example for the paper.On Jan 20, 2024 23:53, Juehang Qin ***@***.***> wrote:
Thank you for the suggestion; do you have any papers on this topic? I couldn't find much about this kind of method with a cursory search; I suppose it is similar to profile likelihoods but I was wondering if there are any papers exploring the statistical properties of this procedure, what the limitations are, etc.

**Comment by juehang** [comment]
I would love to, and I do think I have a model that would be a reasonable use-case (there are 1e2~1e5 latent parameters, depending on dataset, but because those latent parameters correspond to individual events we don't necessarily care about knowing these parameters better than a best-fit estimate).

On top of that, model comparison is something I would be interested in with this model, so nested sampling would be perfect. Would you like to talk about this over zoom or something? Otherwise perhaps we can move this conversation off of the github issue for now 🙂
________________________________

**Comment by Joshuaalbert** [comment]
Yes, sounds like a good idea. Do you have LinkinedIn? [This is my profile](https://www.linkedin.com/in/joshua-g-albert-66734638?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app) and easy to connect there and move to email/zoom.On Jan 21, 2024 22:09, Juehang Qin ***@***.***> wrote:
I would love to, and I do think I have a model that would be a reasonable use-case (there are 1e2~1e5 latent parameters, depending on dataset, but because those latent parameters correspond to individual events we don't necessarily care about knowing these parameters better than a best-fit estimate).



On top of that, model comparison is something I would be interested in with this model, so nested sampling would be perfect. Would you like to talk about this over zoom or something? Otherwise perhaps we can move this conversation off of the github issue for now 🙂

________________________________

From: Joshua George Albert ***@***.***>

Sent: Sunday, January 21, 2024 9:58:35 AM

To: Joshuaalbert/jaxns ***@***.***>

Cc: Juehang Qin ***@***.***>; Author ***@***.***>

Subject: Re: [Joshuaalbert/jaxns] Implementation of Gradient-guided nested sampling (Issue #136)





It's novel, and I will write a paper after I answer some of these questions myself. Are you interested in being a part of the paper? If your example use case is a good fit then it could be the example for the paper.On Jan 20, 2024 23:53, Juehang Qin ***@***.***> wrote:

Thank you for the suggestion; do you have any papers on this topic? I couldn't find much about this kind of method with a cursory search; I suppose it is similar to profile likelihoods but I was wondering if there are any papers exploring the statistical properties of this procedure, what the limitations are, etc.

**Comment by Joshuaalbert** [comment]
Implementing a basic version of this now. Benchmarks show slightly improved estimates of `logZ` and `KL(posterior || prior)` due to faster decorrelation from initial seed points. Note, I use a different approach than in the paper.

![Gradient_guided_vs_baseline_D8_v2 6 4](https://github.com/user-attachments/assets/a3f1b173-1bfb-45d5-95ec-32ce26fa4a95)
