### ISSUE TITLE
[FR] Use single precision by default

### ISSUE THREAD

**Issue by fehiepsi** [Joshuaalbert/jaxns#24]
While working on https://github.com/pyro-ppl/numpyro/pull/807, I recognized that jaxns is changing default precision to double precision. It would be nice to let users decide if they want to change this global setting.

**Comment by Joshuaalbert** [comment]
Hi @fehiepsi there's a note here: https://github.com/Joshuaalbert/jaxns/blob/master/jaxns/__init__.py#L27

I'd love to use float32, but ran into issues long ago with some parts of the code where it comes to adding and subtracting really small numbers, even when using `logaddexp`. I'll check to see if I can relax this now with the current version as there have been a lot of improvements on stability since then.

**Comment by fehiepsi** [comment]
Thanks for the pointer, @Joshuaalbert! Looking at the code, it would be nice to turn `xla_force_host_platform_device_count` off by default too (though I'm not sure if setting it to a high value will have any side effect). :)

**Comment by Joshuaalbert** [comment]
done
