### ISSUE TITLE
Some documentation

### ISSUE THREAD

**Issue by rruizdeaustri** [Joshuaalbert/jaxns#53]
I'm trying to learn how to use jaxns. Is there any documentation about it ?

Thanks a lot !!

Roberto

**Comment by Joshuaalbert** [comment]
Hi @rruizdeaustri nice to hear it!

Firstly, if you're up for it go to [discussions](https://github.com/Joshuaalbert/jaxns/discussions) and make a post introducing yourself and what kinds of problems you'd to like solve with Bayesian computation using JAXNS. I'm trying to get people to post their problems there so that we set up a nice discussion forum for community building.

Secondly, there are a growing number of examples that I post in the [examples section](https://github.com/Joshuaalbert/jaxns/tree/master/examples).

Finally, down the line I'll be rolling out a read the docs.
